stages:
  data_preprocessing:
    cmd: python scripts/data_preprocessing.py
    deps:
      - scripts/data_preprocessing.py
      - params.yaml
    outs:
      - data/processed_data.pkl

  feature_engineering:
    cmd: python scripts/feature_Engineering.py
    deps:
      - scripts/feature_Engineering.py
      - data/processed_data.pkl
      - params.yaml
    outs:
      - data/features.pkl

